
---
# Ansible playbook.yml
# 
# main.yml Vs. 0.0.1-A - 2026/04/10 - Hipervisor KVM

##################################
#                                #
#        Hipervisor KVM          #
#                                #
#         HERMES 001-A           #
#              by                #
#     Vollnet Smart Business     #
#             @2026              #
##################################

# This playbook is designed to provision a VM with Docker, Nginx, Portainer, Node.js, MongoDB
# and Git. Also configures SSH access, sudo permissions, and sets the timezone. The playbook 
# is structured in stages for clarity and modularity.
#
# Usage:
#
# 1. Ensure you have Ansible installed on your control machine.
# 2. Update the inventory file with the target VM's IP address or hostname.
# 3. Run this playbook via Vagrantfile, only!
#

# HERMES Plataform (Mensageiro dos deuses, deus do comércio e viagens)
# 
# Imperativo:
#
#	      VM KVM/QEMU 
#       Vagrant & Ansible 
#       Docker && docker-compose && Portainer 
#       Nginx Live Container 
#       Git 
#       SSH Access
#
# Modalidades (Front-End):
#	
#	      ReactJS 
#       NextJS	
#	      VueJS	
#       Meteor
#       Flask
# 
# Modalidades (Back-End):
#
#     	NestJS 
#	      Django (Back-End)
#       Node & Nodemon & TypeScript 
#
# Modalidades (Data Science)
#
#       Python 3.1X
#
# IA
#
#   	  Ollama (Private IA)
#       Gemini (Google CommercialIA)
#
# Databases:
# 
#      	MongoDB 
#       PostgreSQL
# 

- hosts: all
  become: true
  vars:
    # nginx-1
    nginx_1_port: 3000 
    data_dir_1:   "/home/vagrant/data_1"

    # ollama
    models_path: "/home/vagrant/ollama_data/models"
    ollama_data: "/home/vagrant/ollama_data"
    ollama_model: "llama3"
    ollama_port:  11434

    # Python 
    python_version: "3.14.4"  # Alterar para a versão desejada
    python_install_dir: "/usr/local"

    # Docker and Docker-Compose
    vm_name:      "project_00"
    docker_compose_version: "2.29.1"

    # General variables
    timezone:   "America/Sao_Paulo"
 
    #
    # Projeto:
    #
    vm_project:      "Docker-Work-00" 
    type_project:    "Frontend && Backend Development"
    project_version: "001-A"
    codename:        "HERMES"
    hypervisor:      "KVM/QEMU"
    device:          "Laptop DELL Inspiron"
    status_project:  "Teste Operacional..."

  tasks:
    # Stage-1 Initial Setup
    #  
    # Initial e-mail notification of provisioning completion

    - name: Capturar o ano atual
      ansible.builtin.set_fact:
        ano_atual: "{{ now(fmt='%Y') }}"

    - name: Exibir a mensagem formatada
      ansible.builtin.debug:
        msg: "Vollnet @{{ ano_atual }}"

    - name: Vollnet sending an e-mail using Gmail SMTP servers
      community.general.mail:
        host: smtp.gmail.com
        port: 587 # or 465
        username: vollnet.br@gmail.com
        password: dgsw givp oibr jgut
        to: Celso Eugenio <celso.eugenio@yahoo.com.br>
        subject: 'Vollnet - Initialized provisioning on device {{ device }} - Project {{ project_version }}' 
        body: 
          <html>
          <body>
          <h2>Automated Provisioning Summary</h2>
          <p>This is an automated report from {{ device}}, Provisioning Initialized!</p>

          <table border="1">
            <tr>
              <th> Plataform </th>
              <th> Local </th>
              <th> VM Project </th>
              <th> Type Project </th>
              <th> Version </th>
              <th> Hipervisor </th>
            </tr>
            <tr>
              <td>  {{ codename }}  </td>
              <td>  {{ device }}  </td>
              <td>  {{ vm_project }}  </td>
              <td>  {{ type_project }}  </td>
              <td>  {{ project_version }}  </td>
              <td>  {{ hypervisor }}  </td>
            </tr>
          </table>

            <div>
            <h3> {{ codename }} Plataform</h3>
              <ul>
                <li> VM KVM/QEMU  </li>
                <li> Vagrant & Ansible </li>
                <li> Docker && docker-compose && Portainer </li> 
                <li> NGinx Live Container </li>
                <li> Git </li>
                <li> SSH Access </li>
                <li> ------------------------------------- </li>
                <li> NodeJS & Nodemon </li>
                <li> TypeScript </li>
                <li> -------------------------------------- </li>
                <li> MongoDB </li>
                <li> PostgreSQL </li>
                <li> ------------------------------------- </li>
                <li> Python {{ python_version }} </li>
                <li> Django </li>
                <li> Flask </li>
                <li> ------------------------------------- </li>
                <li> Ollama Private IA </li>
              </ul>
            </div>

            <div>
              <table border="1">
                <tr>
                  <th> Status Project </th>>
                </tr>
                <tr>
                  <td>  {{ status_project }}  </td>
                </tr>
              </table>
            </div>

          <p> Mensagem Automática, Favor não Responder! - Vollnet Smart Bussiness @2026</p>
          </body>
          </html>   
        subtype: html
        secure: starttls 
      delegate_to: localhost  

    - name: Set timezone to America/Sao_Paulo
      community.general.timezone:
        name: America/Sao_Paulo

    - name: Current date initial automation
      debug:
        msg: "{{ '%Y-%m-%d' | strftime }}"

    - name: Current time initial automation
      debug:
        msg: "{{ '%H:%M:%S' | strftime }}"

    - name: Initial ping VM target
      ping:

    - name: Atualizar apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Copy sudoers file config from vm-work to vm-guest
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/
        mode: '0440'
      loop:
        - /home/vollnet/vms-vollnet/{{ vm_name }}/configs/sudoers

    - name: Copy ssh-config file from vm-work to vm-guest
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/ssh/
        mode: '0644'
      loop:
        - /home/vollnet/vms-vollnet/{{ vm_name }}/configs/sshd_config

    - name: Instalar dependências de compilação e ferramentas
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - software-properties-common          
          - build-essential
          - libssl-dev
          - libbz2-dev
          - zlib1g-dev
          - libncurses5-dev
          - libncursesw5-dev
          - libreadline-dev
          - libsqlite3-dev
          - libgdbm-dev
          - db5.3-util
          - libdb5.3-dev
          - libc6-dev
          - libexpat1-dev
          - liblzma-dev
          - liblzma-dev 
          - tk-dev
          - tcl-dev    
          - libffi-dev
          - uuid-dev
          - openssl
          - wget
          - curl
          - net-tools
          - gcc
          - make
          - xz-utils          
        state: present

    # Stage-2 Vagrant Configuration
    #
    - name: Set PasswordAuthentication for the VM-Vagrant
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication yes'

    - name: Set User Group for the VM-Vagrant
      user:
        name: vagrant
        shell: /bin/bash
        groups: sudo
        append: yes

    - name: Permission for user vagrant
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%vagrant'
        line: '%vagrant ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Add public key for vagrant user
      authorized_key:
        user: vagrant
        key: "{{ lookup('file', '/home/vollnet/.ssh/id_ed25519.pub') }}"
        state: present

    # Stage-3 Python Install   <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    
    - name: Python {{ python_version }} - Check that the /usr/local/bin/{{ python_version }} exists
      stat:
        path: /usr/local/bin/{{ python_version }}
      tags: python
      register: python_result
      become: yes

    - name: Update apt-cache for Python
      apt: update_cache=yes
      tags: packages, python
      when: python_result.stat.exists == False
      become: yes

    - name: Extract python  into /tmp
      unarchive:
        src: https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tar.xz
        dest: /tmp/
        remote_src: yes
      tags: packages, python
      become: yes

    - name: Configure python {{ python_version }}
      shell: ./configure chdir=/tmp/Python-{{ python_version }}
      tags: packages, python
      when: python_result.stat.exists == False
      become: yes

    - name: Make Python-{{ python_version }}
      shell: make chdir=/tmp/Python-{{ python_version }}
      tags: packages, python
      when: python_result.stat.exists == False
      become: yes

    - name: Install Python {{ python_version }}
      shell: make install chdir=/tmp/Python-{{ python_version }}
      become_user: root
      tags: packages, python
      when: python_result.stat.exists == False
      become: yes

    - name: Remove tmp files used for Python {{ python_version }} installation
      file: path={{ item }} state=absent
      with_items:
        - /tmp/Python.tar.xz
        - /tmp/Python-{{ python_version }}
      tags: packages, python
      when: python_result.stat.exists == False
      become: yes

    - name: Install requirements for Python package 
      package:
        name:
          - python3-pip
          - python3-dev
          - python3-setuptools
          - python3-venv
        state: present
      become: true

    # Stage-4 Docker Instalation
    # 
    - name: Adicionar chave GPG do Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionar repositório oficial do Docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present

    - name: Instalar Docker SDK para Python (necessário para ansible docker module)
      pip:
        name: docker

    - name: Garantir que o usuário vagrant esteja no grupo docker
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Criar diretório de dados'/home/vagrant/home/vagrant/ollama_data/models'
      file:
        path: "{{ data_dir_1 }}"
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Download docker-compose {{ docker_compose_version }}
      get_url:
        url : https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
        dest: ~/docker-compose
        mode: '+x'
      register: is_installed
      failed_when: no
      changed_when: no
      become: yes

    - name: Check docker-compose exists
      stat: path=~/docker-compose
      register: docker_compose
      become: yes

    - name: Move docker-compose to /usr/local/bin/docker-compose
      command: mv ~/docker-compose /usr/local/bin/docker-compose
      when: docker_compose.stat.exists
      register: is_installed
      failed_when: no
      changed_when: no
      become: yes

    # Stage-5 Nginx Container Setup
    # 
    - name: Rodar contêiner nginx-1
      docker_container:
        name: nginx-1
        image: nginx:latest
        restart_policy: unless-stopped
        ports:
        # Mapeia a porta do host para a porta do contêiner
          - "{{ nginx_1_port }}:{{ 80 }}"
        volumes:
          - "{{ data_dir_1 }}:/home/node/.nginx-1"
        env:
          NGINX_SECURE_COOKIE: "false" # Desabilita cookies seguros para desenvolvimento local
                                       # Em produção, considere configurar um domínio e usar cookies seguros
                                       # fazendo  N8N_SECURE_COOKIE: "true"
          GENERIC_TIMEZONE: "{{ timezone }}"
          TZ: "{{ timezone }}"
        state: started

    # Stage-6 Portainer Container Setup
    #  
    # Docker Portainer - Vs 2.20.X for Docker Vs 26.X.Y and up
    #                    Vs 2.20.3 and up with support for MicroK8S 1.30 
    #
    # see: https://docs.portainer.io/start/install-ce/server/docker/linux
    #
    - name: Creating the VOLUME for Portainer
      command: docker volume create portainer_data
      register: is_installed
      failed_when: no
      changed_when: no
      become: yes      
     
    - name: create the Portainer container
      command: docker run -d -p 8000:8000 -p 9000:9000 --name portainer \
               --restart=always \
               -v /var/run/docker.sock:/var/run/docker.sock \
               -v portainer_data:/data \
               portainer/portainer-ce:latest
      register: is_installed
      failed_when: no
      changed_when: no
      become: yes

    # Access container Portainer Server
    #
    # User: admin
    # Pw:   Portainer#20@ (Change pw after first login)
    #
    # Acess: <Ip-VM_Work>:9000

    # Stage-7 Node.JS && Nodemon && TypeScript
    #
    - name: NodeSource package key
      apt_key:
        state: present
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

    - name: NodeSource Repository
      shell: 'curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -'

    - name: Install NodeJS
      apt:
        state: present
        name: nodejs

    - name: Install nodemon
      npm:
        name: nodemon
        global: yes
        state: present

    - name: Install TypeScript
      npm:
        name: typescript
        global: yes
        state: latest

    # Stage-8 Databases   <<<<<<<<<<<<<<<<<<<<<<<<<<<
    #
    # MongoDB
    #  
    - name: Adicionar chave GPG do MongoDB
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-6.0.asc
        state: present
      become: yes

    - name: Adicionar repositório do MongoDB
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse
        state: present
      become: yes

    - name: Atualizar cache do APT para MongoDB
      apt:
        update_cache: yes
      become: yes

    - name: Instalar MongoDB
      apt:
        name: mongodb-org
        state: latest
        update_cache: yes
      become: yes

    - name: Iniciar e habilitar o serviço do MongoDB
      systemd:
        name: mongod
        state: started
        enabled: yes
      become: yes

    # Checar STATUS após instalação:
    #
    # $ service mongod status
    #

    # PostgreSQL
    #
    - name: Instalar PostgreSQL
      ansible.builtin.apt:
        name: 
          - postgresql
          - postgresql-contrib
          - python3-psycopg2 # Necessário para módulos de DB do Ansible
        state: present

    - name: Garantir que o PostgreSQL está rodando
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: yes

    # Checar STATUS após instalação:
    #
    # $ service postgresql status,  Se Ativo: active (running)
    # 
    # Usuário padrão: postgres
    #
    # Para ter acesso ao prompt do PostgreSQL:
    #
    # $ sudo -i -u postgres psql
    #
    # ou,
    #
    # $ sudo -u postgres psql
    #
    # Para sair do prompt do PostgreSQL:
    #
    # postgres=# \q 
    #
    # ou,
    #
    # postgres=# exit
    #
    # Para verificar a versão do PostgreSQL:
    #
    # $ psql -U postgres -c "SELECT version();"
    #

    # Stage-9 Ollama Private IA  <<<<<<<<<<<<<<<<<<<<<<<<<<<
    #
    # - name: Run the Ollama container
    #   community.docker.docker_container:
    #     name: ollama
    #     image: ollama/ollama:latest
    #     state: started
    #     restart_policy: always
    #     published_ports:
    #       - "11434:11434"
    #     volumes:
    #       - "{{ ollama_data }}:/root/.ollama"

    # - name: Wait for the Ollama service to be ready inside the container
    #   ansible.builtin.wait_for:
    #     port: "{{ ollama_port }}"
    #     timeout: 60
    #     state: started
    #     delay: 5

    # - name: Garantir que o diretório de dados existe
    #   ansible.builtin.file:
    #     path: "{{ models_path }}"
    #     state: directory
    #     owner: vagrant
    #     group: vagrant
    #     mode: '0755'

    # - name: Carregar o modelo llama3
    #   ansible.builtin.command:
    #     cmd: docker exec ollama ollama run {{ ollama_model }}
    #   register: model_pull
    #   changed_when: "'success' in model_pull.stdout"
      
    # - name: Confirmar modelos instalados
    #   ansible.builtin.command:
    #     cmd: docker exec ollama ollama list
    #   register: ollama_list

    # - name: Mostrar modelos ativos
    #   ansible.builtin.debug:
    #     var: ollama_list.stdout_lines

    # Stage-10 Git Latest
    #
    - name: Update APT package manager repositories cache
      apt:
        update_cache: yes

    - name: Install Git Package
      apt:
        name: git
        state: latest
        update_cache: yes

    # Stage-99 Finishing
    #
    # Atualizar e limpar o sistema após a configuração
    - name: Upgrade all apt packages after provision
      apt:
        upgrade: dist
        update_cache: yes

    # Remover pacotes antigos e desnecessários  
    - name: Remove old packages
      apt:
        autoremove: yes
        purge: yes

    # Limpar cache do apt para liberar espaço
    - name: Final ping VM target
      ping:

    # Final date and time automation
    - name: Current date final automation
      debug:
        msg: "{{ '%Y-%m-%d' | strftime }}"

    - name: Current time final automation
      debug:
        msg: "{{ '%H:%M:%S' | strftime }}"

    # Final e-mail notification of provisioning completion
    - name: Vollnet sending an e-mail using Gmail SMTP servers
      community.general.mail:
        host: smtp.gmail.com
        port: 587 # or 465
        username: vollnet.br@gmail.com
        password: dgsw givp oibr jgut
        to: Celso Eugenio <celso.eugenio@yahoo.com.br>
        subject: 'Vollnet - Provisioning completed on the device {{ device }} - Project {{ project_version }}' 
        body: 
          <html>
          <body>
          <h2>Automated Provisioning Summary</h2>
          <p>This is an automated report from {{ device}}, end of Provisioning!</p>
          <table border="1">
            <tr>
              <th> Plataform </th>
              <th> Local </th>
              <th> VM Project </th>
              <th> Type Project </th>
              <th> Version </th>
              <th> Hipervisor </th>
            </tr>
            <tr>
              <td>  {{ codename }}  </td>
              <td>  {{ device }}  </td>
              <td>  {{ vm_project }}  </td>
              <td>  {{ type_project }}  </td>
              <td>  {{ project_version }}  </td>
              <td>  {{ hypervisor }}  </td>
            </tr>
          </table>
          <p> Mensagem Automática, Favor não Responder! - Vollnet Smart Bussiness @2026</p>
          </body>
          </html>  
        subtype: html
        secure: starttls 
      delegate_to: localhost

#
# End of playbook.yml
